wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.17
    cli_version: 0.15.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1693633246.890469
    t:
      1:
      - 1
      - 33
      - 40
      - 55
      3:
      - 13
      - 14
      - 23
      4: 3.9.17
      5: 0.15.9
      8:
      - 5
